/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCatalogSearchRouteImport } from './routes/_authenticated/catalog/search'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedCatalogManufacturersIndexRouteImport } from './routes/_authenticated/catalog/manufacturers/index'
import { Route as AuthenticatedCatalogFranchiseIndexRouteImport } from './routes/_authenticated/catalog/$franchise/index'
import { Route as AuthenticatedCatalogManufacturersSlugIndexRouteImport } from './routes/_authenticated/catalog/manufacturers/$slug/index'
import { Route as AuthenticatedCatalogFranchiseItemsIndexRouteImport } from './routes/_authenticated/catalog/$franchise/items/index'
import { Route as AuthenticatedCatalogFranchiseCharactersIndexRouteImport } from './routes/_authenticated/catalog/$franchise/characters/index'
import { Route as AuthenticatedCatalogManufacturersSlugItemsRouteImport } from './routes/_authenticated/catalog/manufacturers/$slug/items'
import { Route as AuthenticatedCatalogFranchiseItemsSlugRouteImport } from './routes/_authenticated/catalog/$franchise/items/$slug'
import { Route as AuthenticatedCatalogFranchiseCharactersSlugRouteImport } from './routes/_authenticated/catalog/$franchise/characters/$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCatalogSearchRoute =
  AuthenticatedCatalogSearchRouteImport.update({
    id: '/catalog/search',
    path: '/catalog/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCatalogManufacturersIndexRoute =
  AuthenticatedCatalogManufacturersIndexRouteImport.update({
    id: '/catalog/manufacturers/',
    path: '/catalog/manufacturers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogFranchiseIndexRoute =
  AuthenticatedCatalogFranchiseIndexRouteImport.update({
    id: '/catalog/$franchise/',
    path: '/catalog/$franchise/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersSlugIndexRoute =
  AuthenticatedCatalogManufacturersSlugIndexRouteImport.update({
    id: '/catalog/manufacturers/$slug/',
    path: '/catalog/manufacturers/$slug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogFranchiseItemsIndexRoute =
  AuthenticatedCatalogFranchiseItemsIndexRouteImport.update({
    id: '/catalog/$franchise/items/',
    path: '/catalog/$franchise/items/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogFranchiseCharactersIndexRoute =
  AuthenticatedCatalogFranchiseCharactersIndexRouteImport.update({
    id: '/catalog/$franchise/characters/',
    path: '/catalog/$franchise/characters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogManufacturersSlugItemsRoute =
  AuthenticatedCatalogManufacturersSlugItemsRouteImport.update({
    id: '/catalog/manufacturers/$slug/items',
    path: '/catalog/manufacturers/$slug/items',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogFranchiseItemsSlugRoute =
  AuthenticatedCatalogFranchiseItemsSlugRouteImport.update({
    id: '/catalog/$franchise/items/$slug',
    path: '/catalog/$franchise/items/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogFranchiseCharactersSlugRoute =
  AuthenticatedCatalogFranchiseCharactersSlugRouteImport.update({
    id: '/catalog/$franchise/characters/$slug',
    path: '/catalog/$franchise/characters/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/catalog/search': typeof AuthenticatedCatalogSearchRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/catalog/$franchise/': typeof AuthenticatedCatalogFranchiseIndexRoute
  '/catalog/manufacturers/': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/catalog/$franchise/characters/$slug': typeof AuthenticatedCatalogFranchiseCharactersSlugRoute
  '/catalog/$franchise/items/$slug': typeof AuthenticatedCatalogFranchiseItemsSlugRoute
  '/catalog/manufacturers/$slug/items': typeof AuthenticatedCatalogManufacturersSlugItemsRoute
  '/catalog/$franchise/characters/': typeof AuthenticatedCatalogFranchiseCharactersIndexRoute
  '/catalog/$franchise/items/': typeof AuthenticatedCatalogFranchiseItemsIndexRoute
  '/catalog/manufacturers/$slug/': typeof AuthenticatedCatalogManufacturersSlugIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/catalog/search': typeof AuthenticatedCatalogSearchRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/catalog/$franchise': typeof AuthenticatedCatalogFranchiseIndexRoute
  '/catalog/manufacturers': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/catalog/$franchise/characters/$slug': typeof AuthenticatedCatalogFranchiseCharactersSlugRoute
  '/catalog/$franchise/items/$slug': typeof AuthenticatedCatalogFranchiseItemsSlugRoute
  '/catalog/manufacturers/$slug/items': typeof AuthenticatedCatalogManufacturersSlugItemsRoute
  '/catalog/$franchise/characters': typeof AuthenticatedCatalogFranchiseCharactersIndexRoute
  '/catalog/$franchise/items': typeof AuthenticatedCatalogFranchiseItemsIndexRoute
  '/catalog/manufacturers/$slug': typeof AuthenticatedCatalogManufacturersSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/catalog/search': typeof AuthenticatedCatalogSearchRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/catalog/$franchise/': typeof AuthenticatedCatalogFranchiseIndexRoute
  '/_authenticated/catalog/manufacturers/': typeof AuthenticatedCatalogManufacturersIndexRoute
  '/_authenticated/catalog/$franchise/characters/$slug': typeof AuthenticatedCatalogFranchiseCharactersSlugRoute
  '/_authenticated/catalog/$franchise/items/$slug': typeof AuthenticatedCatalogFranchiseItemsSlugRoute
  '/_authenticated/catalog/manufacturers/$slug/items': typeof AuthenticatedCatalogManufacturersSlugItemsRoute
  '/_authenticated/catalog/$franchise/characters/': typeof AuthenticatedCatalogFranchiseCharactersIndexRoute
  '/_authenticated/catalog/$franchise/items/': typeof AuthenticatedCatalogFranchiseItemsIndexRoute
  '/_authenticated/catalog/manufacturers/$slug/': typeof AuthenticatedCatalogManufacturersSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/settings'
    | '/admin/users'
    | '/catalog/search'
    | '/admin/'
    | '/catalog/'
    | '/catalog/$franchise/'
    | '/catalog/manufacturers/'
    | '/catalog/$franchise/characters/$slug'
    | '/catalog/$franchise/items/$slug'
    | '/catalog/manufacturers/$slug/items'
    | '/catalog/$franchise/characters/'
    | '/catalog/$franchise/items/'
    | '/catalog/manufacturers/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/catalog/search'
    | '/admin'
    | '/catalog'
    | '/catalog/$franchise'
    | '/catalog/manufacturers'
    | '/catalog/$franchise/characters/$slug'
    | '/catalog/$franchise/items/$slug'
    | '/catalog/manufacturers/$slug/items'
    | '/catalog/$franchise/characters'
    | '/catalog/$franchise/items'
    | '/catalog/manufacturers/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/users'
    | '/_authenticated/catalog/search'
    | '/_authenticated/admin/'
    | '/_authenticated/catalog/'
    | '/_authenticated/catalog/$franchise/'
    | '/_authenticated/catalog/manufacturers/'
    | '/_authenticated/catalog/$franchise/characters/$slug'
    | '/_authenticated/catalog/$franchise/items/$slug'
    | '/_authenticated/catalog/manufacturers/$slug/items'
    | '/_authenticated/catalog/$franchise/characters/'
    | '/_authenticated/catalog/$franchise/items/'
    | '/_authenticated/catalog/manufacturers/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/catalog/search': {
      id: '/_authenticated/catalog/search'
      path: '/catalog/search'
      fullPath: '/catalog/search'
      preLoaderRoute: typeof AuthenticatedCatalogSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/catalog/manufacturers/': {
      id: '/_authenticated/catalog/manufacturers/'
      path: '/catalog/manufacturers'
      fullPath: '/catalog/manufacturers/'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$franchise/': {
      id: '/_authenticated/catalog/$franchise/'
      path: '/catalog/$franchise'
      fullPath: '/catalog/$franchise/'
      preLoaderRoute: typeof AuthenticatedCatalogFranchiseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/$slug/': {
      id: '/_authenticated/catalog/manufacturers/$slug/'
      path: '/catalog/manufacturers/$slug'
      fullPath: '/catalog/manufacturers/$slug/'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$franchise/items/': {
      id: '/_authenticated/catalog/$franchise/items/'
      path: '/catalog/$franchise/items'
      fullPath: '/catalog/$franchise/items/'
      preLoaderRoute: typeof AuthenticatedCatalogFranchiseItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$franchise/characters/': {
      id: '/_authenticated/catalog/$franchise/characters/'
      path: '/catalog/$franchise/characters'
      fullPath: '/catalog/$franchise/characters/'
      preLoaderRoute: typeof AuthenticatedCatalogFranchiseCharactersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/manufacturers/$slug/items': {
      id: '/_authenticated/catalog/manufacturers/$slug/items'
      path: '/catalog/manufacturers/$slug/items'
      fullPath: '/catalog/manufacturers/$slug/items'
      preLoaderRoute: typeof AuthenticatedCatalogManufacturersSlugItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$franchise/items/$slug': {
      id: '/_authenticated/catalog/$franchise/items/$slug'
      path: '/catalog/$franchise/items/$slug'
      fullPath: '/catalog/$franchise/items/$slug'
      preLoaderRoute: typeof AuthenticatedCatalogFranchiseItemsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$franchise/characters/$slug': {
      id: '/_authenticated/catalog/$franchise/characters/$slug'
      path: '/catalog/$franchise/characters/$slug'
      fullPath: '/catalog/$franchise/characters/$slug'
      preLoaderRoute: typeof AuthenticatedCatalogFranchiseCharactersSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogSearchRoute: typeof AuthenticatedCatalogSearchRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedCatalogFranchiseIndexRoute: typeof AuthenticatedCatalogFranchiseIndexRoute
  AuthenticatedCatalogManufacturersIndexRoute: typeof AuthenticatedCatalogManufacturersIndexRoute
  AuthenticatedCatalogFranchiseCharactersSlugRoute: typeof AuthenticatedCatalogFranchiseCharactersSlugRoute
  AuthenticatedCatalogFranchiseItemsSlugRoute: typeof AuthenticatedCatalogFranchiseItemsSlugRoute
  AuthenticatedCatalogManufacturersSlugItemsRoute: typeof AuthenticatedCatalogManufacturersSlugItemsRoute
  AuthenticatedCatalogFranchiseCharactersIndexRoute: typeof AuthenticatedCatalogFranchiseCharactersIndexRoute
  AuthenticatedCatalogFranchiseItemsIndexRoute: typeof AuthenticatedCatalogFranchiseItemsIndexRoute
  AuthenticatedCatalogManufacturersSlugIndexRoute: typeof AuthenticatedCatalogManufacturersSlugIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogSearchRoute: AuthenticatedCatalogSearchRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedCatalogFranchiseIndexRoute:
    AuthenticatedCatalogFranchiseIndexRoute,
  AuthenticatedCatalogManufacturersIndexRoute:
    AuthenticatedCatalogManufacturersIndexRoute,
  AuthenticatedCatalogFranchiseCharactersSlugRoute:
    AuthenticatedCatalogFranchiseCharactersSlugRoute,
  AuthenticatedCatalogFranchiseItemsSlugRoute:
    AuthenticatedCatalogFranchiseItemsSlugRoute,
  AuthenticatedCatalogManufacturersSlugItemsRoute:
    AuthenticatedCatalogManufacturersSlugItemsRoute,
  AuthenticatedCatalogFranchiseCharactersIndexRoute:
    AuthenticatedCatalogFranchiseCharactersIndexRoute,
  AuthenticatedCatalogFranchiseItemsIndexRoute:
    AuthenticatedCatalogFranchiseItemsIndexRoute,
  AuthenticatedCatalogManufacturersSlugIndexRoute:
    AuthenticatedCatalogManufacturersSlugIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
